text_file = open("students5.txt", "wt")
text_file.write("Ершов Болеслав, 1.3 балов\n")
text_file.write("Шевченко Святослав, 7.4 балов\n")
text_file.write("Лаврентьева Татьяна, 9 балов\n")
text_file.write("Федотова Элина, 1.5 балов\n")
text_file.write("Шарапов Любомир, 5 балов\n")
text_file.write("Исаева Алиса, 1 балов\n")
text_file.write("Гриневска Вера, 7.5 балов\n")
text_file.write("Шевченко Максим, 9.3 балов\n")
text_file.write("Бобылёва Владислава, 2.5 балов\n")
text_file.write("Дементьева Анжелика, 8.1 балов\n")
text_file.close()

text_file = open("students6.txt", "wt")
text_file.write("Евсеева Аксинья, 1.6 балов\n")
text_file.write("Трофимов Юрий, 4.5 балов\n")
text_file.write("Ефимов Бенедикт, 7 балов\n")
text_file.write("Сасько Изольда, 1.8 балов\n")
text_file.write("Шилова Ираида, 3 балов\n")
text_file.write("Иванкова Харита, 3.9 балов\n")
text_file.write("Белозёров Любомир, 8.9 балов\n")
text_file.write("Белоусова Аза, 3 балов\n")
text_file.close()

text_file = open("students7.txt", "wt")
text_file.write("Лаврентьев Альберт, 5.8 балов\n")
text_file.write("Жуков Валерий, 4 балов\n")
text_file.write("Мамонтова Людмила, 1.9 балов\n")
text_file.write("Алексеева Альвина, 7.6 балов\n")
text_file.write("Аксёнова Харитина, 8.2 балов\n")
text_file.write("Никифоров Харитон, 9 балов\n")
text_file.write("Архипов Константин, 2 балов\n")
text_file.write("Гуляева Гертруда, 1 балов\n")
text_file.close()
